import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Logo from "../../public/images/wowLogo.png";
import nav_catThumbsUp from "../../public/images/nav-catThumbsUp.svg";
import nav_socialbox from "../../public/images/nav-socialbox.svg";

import linkedin from "../../public/images/icons/socials/linkedin.svg";
import x from "../../public/images/icons/socials/x.svg";
import facebook from "../../public/images/icons/socials/facebook.svg";
import instagram from "../../public/images/icons/socials/instagram.svg";

import linkedin_white from "../../public/images/icons/socials/linkedin-white.svg";
import x_white from "../../public/images/icons/socials/x-white.svg";
import facebook_white from "../../public/images/icons/socials/facebook-white.svg";
import instagram_white from "../../public/images/icons/socials/instagram-white.svg";

const alexandria = Alexandria({
  variable: "--font-alexandria",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WoW Meow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alexandria.className} antialiased`}>
        <header className="bg-customBlack h-[80px]">
          <div className="relative mx-auto flex max-w-[1920px] items-center justify-between px-[60px]">
            <Link href={"/"}>
              <Image
                className="relative top-4 left-4 scale-[120%] transition-transform duration-300 hover:scale-[140%]"
                src={Logo}
                height={80}
                alt="WoWMeow logo"
              ></Image>
            </Link>
            <nav className="absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]">
              <ul className="text-customWhite text-nowrap flex gap-[40px] text-(length:--font-sm-plus) uppercase">
                <li className="hover:text-customYellow transition-colors duration-300">
                  <Link href={"/"}>Games</Link>
                </li>
                <li className="hover:text-customYellow transition-colors duration-300">
                  <Link href={"/about"}>About</Link>
                </li>
                <li className="hover:text-customYellow transition-colors duration-300">
                  <Link href={"/investors"}>For Investors</Link>
                </li>
                <li className="hover:text-customYellow transition-colors duration-300">
                  <Link href={"/services"}>Services</Link>
                </li>
                <li className="hover:text-customYellow transition-colors duration-300">
                  <Link href={"/contacts"}>Contacts</Link>
                </li>
              </ul>
            </nav>
            <div className="relative top-1 left-1 flex items-start">
              <Image
                src={nav_catThumbsUp}
                alt="A smiling cat holding a controller, giving the thumbs up."
              ></Image>
              <div className="relative flex shrink-0">
                <Image aria-hidden src={nav_socialbox} alt=""></Image>
                <ul className="absolute top-[6px] right-[8px] flex gap-2.5">
                  <li>
                    {" "}
                    <Link href={"https://linkedin.com"}>
                      <Image
                        className="transition-transform duration-150 hover:rotate-12"
                        src={linkedin}
                        alt="linkedin logo"
                        width={30}
                        height={30}
                      ></Image>
                    </Link>
                  </li>
                  <li>
                    {" "}
                    <Link href={"https://instagram.com"}>
                      <Image
                        className="transition-transform duration-150 hover:rotate-[-12deg]"
                        src={instagram}
                        alt="instagram logo"
                        width={30}
                        height={30}
                      ></Image>
                    </Link>
                  </li>
                  <li>
                    {" "}
                    <Link href={"https://facebook.com"}>
                      <Image
                        className="transition-transform duration-150 hover:rotate-12"
                        src={facebook}
                        alt="facebook logo"
                        width={30}
                        height={30}
                      ></Image>
                    </Link>
                  </li>
                  <li>
                    {" "}
                    <Link href={"https://x.com"}>
                      <Image
                        className="transition-transform duration-150 hover:rotate-[-12deg]"
                        src={x}
                        alt="x logo"
                        width={30}
                        height={30}
                      ></Image>
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </header>
        {children}
        <footer className="bg-customBlack absolute right-0 bottom-0 left-0 px-[60px] pt-[15px] pb-[10px]">
          <div className="mx-auto mb-[35px] flex max-w-[1920px] justify-between">
            <div className="mt-[10px] flex gap-[60px]">
              <div>
                <h2 className="mb-[40px] text-customWhite text-(length:--font-md) font-bold uppercase">
                  Connect with us:
                </h2>
                <ul>
                  <ul className="flex gap-2.5">
                    <li>
                      {" "}
                      <Link href={"https://instagram.com"}>
                        <Image
                          className="transition-transform duration-150 hover:rotate-[-12deg]"
                          src={instagram_white}
                          alt="instagram logo"
                          width={40}
                          height={40}
                        ></Image>
                      </Link>
                    </li>
                    <li>
                      {" "}
                      <Link href={"https://facebook.com"}>
                        <Image
                          className="transition-transform duration-150 hover:rotate-12"
                          src={facebook_white}
                          alt="facebook logo"
                          width={40}
                          height={40}
                        ></Image>
                      </Link>
                    </li>
                    <li>
                      {" "}
                      <Link href={"https://x.com"}>
                        <Image
                          className="transition-transform duration-150 hover:rotate-[-12deg]"
                          src={x_white}
                          alt="x logo"
                          width={40}
                          height={40}
                        ></Image>
                      </Link>
                    </li>
                    <li>
                      {" "}
                      <Link href={"https://linkedin.com"}>
                        <Image
                          className="transition-transform duration-150 hover:rotate-12"
                          src={linkedin_white}
                          alt="linkedin logo"
                          width={40}
                          height={40}
                        ></Image>
                      </Link>
                    </li>
                  </ul>
                </ul>
              </div>
              <div>
                <h2 className="mb-[40px] text-customWhite text-(length:--font-md) font-bold uppercase">
                  Site links:
                </h2>
                <nav>
                  <ul className="text-customWhite flex flex-col gap-[15px] text-(length:--font-sm-plus) uppercase">
                    <li className="hover:text-customYellow transition-colors duration-300">
                      <Link href={"/"}>Games</Link>
                    </li>
                    <li className="hover:text-customYellow transition-colors duration-300">
                      <Link href={"/about"}>About</Link>
                    </li>
                    <li className="hover:text-customYellow transition-colors duration-300">
                      <Link href={"/investors"}>For Investors</Link>
                    </li>
                    <li className="hover:text-customYellow transition-colors duration-300">
                      <Link href={"/services"}>Services</Link>
                    </li>
                    <li className="hover:text-customYellow transition-colors duration-300">
                      <Link href={"/contacts"}>Contacts</Link>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
            <div>
              <h2 className="mb-[40px] mt-[10px] text-customWhite mr-[320px] text-(length:--font-md) font-bold uppercase">
                Email:
              </h2>
              <a
                className="text-customWhite hover:text-customYellow text-(length:--font-sm-plus) uppercase underline transition-colors duration-300"
                href="mailto:info@wow-meow.fun"
              >
                info@wow-meow.fun
              </a>
            </div>
          </div>
          <div className="flex justify-between">
            <p className="text-customWhite text-[14px] uppercase">
              @ copyright 2024 wow meow games
            </p>
            <div className="flex gap-[40px]">
              <Link
                className="text-customWhite hover:text-customYellow text-(length:--font-sm-plus) uppercase transition-colors duration-300"
                href={"/TOS"}
              >
                Privacy policy
              </Link>
              <Link
                className="text-customWhite hover:text-customYellow text-(length:--font-sm-plus) uppercase transition-colors duration-300"
                href={"/TOS"}
              >
                terms & conditions
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
